import { NextResponse } from "next/server";

const countryNames = [
   { "id": 1, "name": "Afghanistan" },
   { "id": 2, "name": "Albania" },
   { "id": 3, "name": "Algeria" },
   { "id": 4, "name": "Andorra" },
   { "id": 5, "name": "Angola" },
   { "id": 6, "name": "Argentina" },
   { "id": 7, "name": "Armenia" },
   { "id": 8, "name": "Australia" },
   { "id": 9, "name": "Austria" },
   { "id": 10, "name": "Azerbaijan" },
   { "id": 11, "name": "Bahamas" },
   { "id": 12, "name": "Bahrain" },
   { "id": 13, "name": "Bangladesh" },
   { "id": 14, "name": "Barbados" },
   { "id": 15, "name": "Belarus" },
   { "id": 16, "name": "Belgium" },
   { "id": 17, "name": "Belize" },
   { "id": 18, "name": "Benin" },
   { "id": 19, "name": "Bhutan" },
   { "id": 20, "name": "Bolivia" },
   { "id": 21, "name": "Bosnia and Herzegovina" },
   { "id": 22, "name": "Botswana" },
   { "id": 23, "name": "Brazil" },
   { "id": 24, "name": "Brunei" },
   { "id": 25, "name": "Bulgaria" },
   { "id": 26, "name": "Burkina Faso" },
   { "id": 27, "name": "Burundi" },
   { "id": 28, "name": "Cambodia" },
   { "id": 29, "name": "Cameroon" },
   { "id": 30, "name": "Canada" },
   { "id": 31, "name": "Central African Republic" },
   { "id": 32, "name": "Chad" },
   { "id": 33, "name": "Chile" },
   { "id": 34, "name": "China" },
   { "id": 35, "name": "Colombia" },
   { "id": 36, "name": "Comoros" },
   { "id": 37, "name": "Congo" },
   { "id": 38, "name": "Costa Rica" },
   { "id": 39, "name": "Croatia" },
   { "id": 40, "name": "Cuba" },
   { "id": 41, "name": "Cyprus" },
   { "id": 42, "name": "Czech Republic" },
   { "id": 43, "name": "Denmark" },
   { "id": 44, "name": "Djibouti" },
   { "id": 45, "name": "Dominican Republic" },
   { "id": 46, "name": "Ecuador" },
   { "id": 47, "name": "Egypt" },
   { "id": 48, "name": "El Salvador" },
   { "id": 49, "name": "Eritrea" },
   { "id": 50, "name": "Estonia" },
   { "id": 51, "name": "Ethiopia" },
   { "id": 52, "name": "Fiji" },
   { "id": 53, "name": "Finland" },
   { "id": 54, "name": "France" },
   { "id": 55, "name": "Gabon" },
   { "id": 56, "name": "Gambia" },
   { "id": 57, "name": "Georgia" },
   { "id": 58, "name": "Germany" },
   { "id": 59, "name": "Ghana" },
   { "id": 60, "name": "Greece" },
   { "id": 61, "name": "Guatemala" },
   { "id": 62, "name": "Guinea" },
   { "id": 63, "name": "Haiti" },
   { "id": 64, "name": "Honduras" },
   { "id": 65, "name": "Hungary" },
   { "id": 66, "name": "Iceland" },
   { "id": 67, "name": "India" },
   { "id": 68, "name": "Indonesia" },
   { "id": 69, "name": "Iran" },
   { "id": 70, "name": "Iraq" },
   { "id": 71, "name": "Ireland" },
   { "id": 72, "name": "Israel" },
   { "id": 73, "name": "Italy" },
   { "id": 74, "name": "Jamaica" },
   { "id": 75, "name": "Japan" },
   { "id": 76, "name": "Jordan" },
   { "id": 77, "name": "Kazakhstan" },
   { "id": 78, "name": "Kenya" },
   { "id": 79, "name": "Kuwait" },
   { "id": 80, "name": "Kyrgyzstan" },
   { "id": 81, "name": "Laos" },
   { "id": 82, "name": "Latvia" },
   { "id": 83, "name": "Lebanon" },
   { "id": 84, "name": "Liberia" },
   { "id": 85, "name": "Libya" },
   { "id": 86, "name": "Lithuania" },
   { "id": 87, "name": "Luxembourg" },
   { "id": 88, "name": "Malaysia" },
   { "id": 89, "name": "Maldives" },
   { "id": 90, "name": "Mali" },
   { "id": 91, "name": "Mexico" },
   { "id": 92, "name": "Moldova" },
   { "id": 93, "name": "Monaco" },
   { "id": 94, "name": "Mongolia" },
   { "id": 95, "name": "Morocco" },
   { "id": 96, "name": "Myanmar" },
   { "id": 97, "name": "Namibia" },
   { "id": 98, "name": "Nepal" },
   { "id": 99, "name": "Netherlands" },
   { "id": 100, "name": "New Zealand" },
   { "id": 101, "name": "Nicaragua" },
   { "id": 102, "name": "Nigeria" },
   { "id": 103, "name": "Norway" },
   { "id": 104, "name": "Oman" },
   { "id": 105, "name": "Pakistan" },
   { "id": 106, "name": "Palestine" },
   { "id": 107, "name": "Panama" },
   { "id": 108, "name": "Paraguay" },
   { "id": 109, "name": "Peru" },
   { "id": 110, "name": "Philippines" },
   { "id": 111, "name": "Poland" },
   { "id": 112, "name": "Portugal" },
   { "id": 113, "name": "Qatar" },
   { "id": 114, "name": "Romania" },
   { "id": 115, "name": "Russia" },
   { "id": 116, "name": "Saudi Arabia" },
   { "id": 117, "name": "South Africa" },
   { "id": 118, "name": "South Korea" },
   { "id": 119, "name": "Spain" },
   { "id": 120, "name": "Sri Lanka" },
   { "id": 121, "name": "Sweden" },
   { "id": 122, "name": "Switzerland" },
   { "id": 123, "name": "Turkey" },
   { "id": 124, "name": "United Kingdom" },
   { "id": 125, "name": "United States" },
   { "id": 126, "name": "Vietnam" }
 ]
 export async function GET(request: Request) {
    // URL se query parameters extract karo
    const { searchParams } = new URL(request.url);
    const query = searchParams.get("query") || ""; // Default empty string
  
    // Search filter apply karo
    const filteredCountries = countryNames.filter((item) =>
      item.name.toLowerCase().includes(query.toLowerCase())
    );
  
    return NextResponse.json(filteredCountries);
  }




  